### PR TITLE
Munish/feature/get articles/backend

### PR DESCRIPTION
**Pull request by munishk686**
👨🏻‍💻 What does this PR do?
The endpoints API has been created to fetch the articles by ID and find all and the range of the year.

🧪 How has/should this change been tested?
The changes have been tested on the Thunder client.

📝 Any notes for the reviewer?

📜 Documentation
Endpoint URL:

**Getting the articles by ID:**
http://localhost:3001/submissions/65192b759bb31ac640773f4a

{
  "_id": "65192b759bb31ac640773f4a",
  "title": "Atomic Habits",
  "authors": "James Clear",
  "journal": "Habits",
  "year": 2018,
  "volume": "1",
  "pages": "250",
  "doi": "18/08/23",
  "__v": 0
}

**Find all the articles.**
http://localhost:3001/submissions

{
    "_id": "65192b4f9bb31ac640773f48",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2017,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  },
  {
    "_id": "65192b759bb31ac640773f4a",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2018,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  },

**Getting the articles by range of years:**
http://localhost:3001/submissions/by-year-range?startYear=2018&endYear=2022

[
  {
    "_id": "65192b759bb31ac640773f4a",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2018,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  },
  {
    "_id": "65192b899bb31ac640773f4c",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2019,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  },
  {
    "_id": "65192b919bb31ac640773f4e",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2020,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  },
  {
    "_id": "65192b969bb31ac640773f50",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2021,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  },
  {
    "_id": "65192b9b9bb31ac640773f52",
    "title": "Atomic Habits",
    "authors": "James Clear",
    "journal": "Habits",
    "year": 2022,
    "volume": "1",
    "pages": "250",
    "doi": "18/08/23",
    "__v": 0
  }
]

### CODE REVIEW

**Comment by MiguelEmmara-ai** [comment]
Hi @munishk686 , good work, can you add documentation to tell us how to use the api end point? is there some sort of special links? security or anything? it will make it easier for the front end team to work with

**Comment by MiguelEmmara-ai** [comment]
@munishk686 also since on the front end, the functionality allow the user to get articles by filtering year, can you do that?

**Comment by munishk686** [comment]
Hi @MiguelEmmara-ai, I have updated the Documentation in the comment section and also updated the functionality getting the articles by years.

**Comment by MiguelEmmara-ai** [comment]
Amazing code, Amazing API documentation
well done brother!

**Pull request merged**
